#!/usr/bin/env python3
"""
sync-ide-folders.py

Mirrors the canonical skills/ directory into IDE-specific subdirectories so the
plugin works on Codex, Cursor, Windsurf, Cline, and OpenCode without each
needing custom code. Run before each release.

Pattern follows planning-with-files scripts/sync-ide-folders.py.
"""

import shutil
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
CANONICAL_SKILLS = ROOT / "skills"
CANONICAL_AGENTS = ROOT / "agents"
CANONICAL_COMMANDS = ROOT / "commands"

IDE_TARGETS = {
    ".codex": {"skills_dir": "skills", "agents_dir": "agents", "commands_dir": "commands"},
    ".cursor": {"skills_dir": "skills", "agents_dir": "agents", "commands_dir": "commands"},
    ".windsurf": {"skills_dir": "skills", "agents_dir": "agents", "commands_dir": "commands"},
    ".clinerules": {"skills_dir": ".", "agents_dir": None, "commands_dir": None},
    ".opencode": {"skills_dir": "skills", "agents_dir": "agents", "commands_dir": "commands"},
}


def clean_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def copy_tree(src: Path, dst: Path) -> int:
    if not src.exists():
        return 0
    count = 0
    for item in src.iterdir():
        target = dst / item.name
        if item.is_dir():
            shutil.copytree(item, target)
            count += sum(1 for _ in target.rglob("*") if _.is_file())
        else:
            shutil.copy2(item, target)
            count += 1
    return count


def sync_one(ide_dir_name: str, layout: dict) -> tuple[int, int, int]:
    ide_root = ROOT / ide_dir_name
    files_skills = files_agents = files_commands = 0

    if layout["skills_dir"] is not None:
        skills_target = ide_root / layout["skills_dir"]
        clean_dir(skills_target)
        files_skills = copy_tree(CANONICAL_SKILLS, skills_target)

    if layout["agents_dir"] is not None:
        agents_target = ide_root / layout["agents_dir"]
        clean_dir(agents_target)
        files_agents = copy_tree(CANONICAL_AGENTS, agents_target)

    if layout["commands_dir"] is not None:
        commands_target = ide_root / layout["commands_dir"]
        clean_dir(commands_target)
        files_commands = copy_tree(CANONICAL_COMMANDS, commands_target)

    # Always rewrite a small README so the mirror is self-explanatory.
    readme = ide_root / "README.md"
    readme.write_text(
        f"# {ide_dir_name} mirror — MDDesign\n\n"
        f"Auto-generated by `scripts/sync-ide-folders.py`. Do not edit by hand.\n"
        f"Edit the canonical sources under `skills/`, `agents/`, `commands/` then run sync again.\n",
        encoding="utf-8",
    )
    return files_skills, files_agents, files_commands


def main() -> int:
    if not CANONICAL_SKILLS.exists():
        print(f"FATAL: canonical skills dir missing at {CANONICAL_SKILLS}", file=sys.stderr)
        return 1

    print(f"MDDesign sync from {ROOT}")
    print(f"  canonical: skills={CANONICAL_SKILLS.name} agents={CANONICAL_AGENTS.name} commands={CANONICAL_COMMANDS.name}")
    total_s = total_a = total_c = 0
    for ide, layout in IDE_TARGETS.items():
        s, a, c = sync_one(ide, layout)
        total_s += s
        total_a += a
        total_c += c
        print(f"  {ide:14s}  skills={s:3d}  agents={a:3d}  commands={c:3d}")
    print(f"\n  totals        skills={total_s:3d}  agents={total_a:3d}  commands={total_c:3d}")
    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
